### ISSUE TITLE
Start of Fieldwork

### ISSUE THREAD

**Issue by MRuzzante** [MRuzzante/Jah-referencing#1]
**Tasks for the DC-based RA**

- [ ] Test the CTO form
- [ ] Prepare HFCs, giving high priority to GPS plotting
- [ ] Rasta-specific checks on survey time
- [ ] Monitor "Don't know/refuse to answer"
- [ ] Check distribution especially on @jonasguthoff's driving behavior and @MRuzzante's balance

Please report back to the field team on a daily basis.
